name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  NEXT_TELEMETRY_DISABLED: 1
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  # Quick fail job - runs basic checks first
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Check lockfile exists
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "❌ pnpm-lock.yaml is missing!"
            echo "Run 'pnpm install' and commit the lockfile"
            exit 1
          fi
          echo "✅ pnpm-lock.yaml exists"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint & Type check (parallel)
        run: |
          pnpm lint &
          lint_pid=$!
          pnpm typecheck &
          type_pid=$!
          
          wait $lint_pid
          lint_exit=$?
          wait $type_pid
          type_exit=$?
          
          if [ $lint_exit -ne 0 ] || [ $type_exit -ne 0 ]; then
            exit 1
          fi

  # Full validation only if quick-check passes
  validate:
    needs: quick-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]  # Only test on latest LTS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: |
          if [ "${{ env.CI_E2E }}" != "false" ]; then
            pnpm test
          else
            echo "E2E tests skipped (CI_E2E=false)"
            CI_E2E=false pnpm test
          fi
        env:
          CI_E2E: ${{ secrets.CI_E2E || 'false' }}

      - name: Check for uncommitted lockfile changes
        run: |
          if git diff --exit-code pnpm-lock.yaml; then
            echo "✅ pnpm-lock.yaml is up to date"
          else
            echo "❌ pnpm-lock.yaml has uncommitted changes"
            echo "Please run 'pnpm install' and commit the changes"
            exit 1
          fi

  # Optional: Test on Node 18 only if needed
  validate-legacy:
    needs: quick-check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: CI_E2E=false pnpm test
